theos/headers

- SpringBoard/SBApplication.h
- SpringBoard/SBBannerView.h
- SpringBoard/SBBulletinBannerController.h
- SpringBoard/SBBulletinBannerView.h
- SpringBoard/SBIconModel.h
This only adds these annotations to headers which had already been marked with availability notes in comments (and `SBApplication` and `SBIconModel`, which I looked up and annotated myself).
> Add deprecation and availability annotations to SpringBoard headers.

- _Prefix/HBLog.h
The NSLog macro in `_Prefix/HBLog.h` causes issues for those who have NSLog macros of their own in their projects. It's a rather noticeable usability issue, and should be removed.
This functionality can be re-added later as a part of [`kirb/theos`](https://github.com/kirb/theos) instead.
> Remove NSLog deprecation macro

- version.h
This commit adds kCFCoreFoundationVersionNumber from iOS 14.1 to 14.3, along with iOS 12.5. Also, kCFCoreFoundationVersionNumber_iOS_14_0 was wrong, now it should be correct (The version number is same as kCFCoreFoundationVersionNumber_iOS_14_1)
> [version] Updated version.h, adding to 14.3

- LightMessaging/LightMessaging.h
- bootstrap.h
- rocketbootstrap/rocketbootstrap.h
`serverName` should be `const name_t` not just `name_t` or you get a warning for pointer decay from a string literal into `char *`
> Resolve std*11 warning in LightMessaging.h

- BluetoothManager/RemoteDeviceManager.h
- BulletinBoard/BBServer.h
- ChatKit/CKTranscriptManagementController.h
- MobileGestalt/MobileGestalt.h
- MobileTimer/WorldClockCollectionCell.h
- Preferences/PSSystemPolicyForApp.h
- PreferencesUI/DevicePINControllerDelegate.h
- PreferencesUI/PSUIPrefsListController.h
- QuartzCore/QuartzCore-Structs.h
- SpringBoard/SBAppSwitcherModel.h
- SpringBoard/SBAppViewController.h
- SpringBoard/SBBBBulletinInfo.h
- SpringBoard/SBBulletinBannerItem.h
- SpringBoard/SBFolderIconView.h
- SpringBoard/SBLockScreenNotificationListController.h
- SpringBoard/SBRootFolder.h
- Tweetbot/PTHAlertViewController.h
- UIKit/UIActivityViewController+Private.h
- UIKit/UITableViewRowAction+Private.h
- UIKit/_UILayerHostView.h
- UserNotificationsUIKit/NCNotificationRequest+Additions.h
These changes predominantly are `@class` declarations to improve importing headers independently. Per the [Code Rules](https://github.com/theos/headers#code-rules), headers should import e.g. Foundation and UIKit as needed. This commit does not include these types of imports as the diff would be substantially large, and I felt like some of these changes were important to get upstream quickly.
Additionally this fixes an issue brought up in https://github.com/theos/headers/commit/559da05801bb52765932af9531338d86f3a95abb#r43825152
> Fix imports and declarations to allow compiling

- AddressBookUI/ABMonogrammer.h
- BiometricKit/BiometricKit.h
- MobileCoreServices/LSAppLink.h
- MobileCoreServices/LSApplicationProxy.h
- MobileCoreServices/LSBundleProxy.h
- MobileCoreServices/LSResourceProxy.h
- MobileCoreServices/_LSQueryResult.h
- SpringBoard/VolumeControl.h
Deprecate `ABMonogrammer` (with replacement)
Adds availability attributes to `MobileCoreServices` classes
Update a few occurrences of `API_DEPRECATED` with `API_DEPRECATED_WITH_REPLACEMENT`
> Availability (`API_{AVAILABLE,DEPRECATED}`) updates

- Foundation/NSXPCConnection.h
A few things to note:
1. I did not use *any* content from the Apple copyright-protected header, all of this was written and edited according to the public Apple documentation and classdump headers.
2. The reason why I rewrote the whole header and didn't just add the private methods in an interface, is because they are marked unavailable for iOS by API_UNAVAILABLE in the original header and redefining them does not do any difference. The header need to be overridden in order for the private methods to be usable, meaning this header needs to be used instead of the original one in the SDK.
> Add NSXPCConnection header with proper declaration of private methods

- MobileGestalt/MobileGestalt.h
- installd/MIDaemonConfiguration.h
- installd/MIGlobalConfiguration.h
There are a couple more properties in MIDaemonConfiguration that I purposely left out because they do not work, the ones left intact do work, but only when dealing with installd directly (Example; https://repo.packix.com/package/daniel.midaemontweak/)
> fix spelling error in MobileGestalt.h + added MIDaemonConfiguration API to installd

- version.h
> [version] Added CoreFoundation versions for iOS 14.6 - 15.3

- ControlCenterUIKit/CCUILabeledRoundButtonViewController.h
- FrontBoardServices/FBSMutableSceneSettings.h
- IOKit/IOMessage.h
- IOKit/hid/IOHIDEventData.h
- IOKit/hid/IOHIDEventTypes.h
- IOKit/ps/IOPSKeys.h
- IOKit/pwr_mgt/IOPMLib.h
- QuartzCore/CAPackage.h
- SpringBoard/SBWorkspaceTransitionContext.h
- UIKit/_UIAssetManager.h
- installd/MIDaemonConfiguration.h
- openssl/asn1.h
- openssl/evp.h
- openssl/pkcs7.h
- openssl/ssl2.h
- openssl/x509v3.h
> [meta] Removed trailing spaces from the headers

- MobileGestalt/MobileGestalt.h
> [MobileGestalt] Added more device classes

- OnBoardingKit/OBPrivacyLinkButton.h
> [OnBoardingKit] Added OBPrivacyLinkButton

- LowPowerMode/_PLLowPowerMode.h
> [LowPowerMode] Added _PLLowPowerMode header (iOS 15+)

- libundirect/libundirect.h
- libundirect/libundirect_dynamic.h
> [libundirect] Updated libundirect headers to version 1.1.4

- rootless.h
Rootless preprocessor macros that handle automatic conversion of paths to `/var/jb` only when building for rootless.
> Add rootless preprocessor macros

- version.h
Added CoreFoundation versions for iOS 16.0 / 16.1 / 16.4
Checklist
---------
…
…
> [version] Added CoreFoundation versions for iOS 16.0 / 16.1 / 16.4

- BulletinBoard/BBBulletin.h
- Contacts/CNContact+Private.h
- Contacts/CNContactFormatter+Private.h
- Contacts/CNPhoneNumber+Private.h
- ControlCenterUIKit/CCUILabeledRoundButton.h
- MapKit/MKMapItem+Private.h
- UserNotificationsUIKit/NCNotificationRequest+Additions.h
Enables more headers to be imported by themselves.
Checklist
---------
…
…
This unblocks #72 
**Operating System:** Ubuntu, macOS
**Target Platform:** iOS
**SDK Version:** iOS 14.5
> Import and forward-declare classes as needed to compile headers

- FrontBoardServices/FBSSystemService.h
Adds extra methods to FBSSystemService.h
Checklist
---------
…
…
> More methods for FBSSystemService.h

- rootless.h
This removes the code checking whether `THEOS_PACKAGE_INSTALL_PREFIX` is define, as this is now always defined.
Additionally it introduces backwards support for xina with the define `XINA_SUPPORT` that a dev can set inside the Makefile if Xina support is desired. Note that this should only be set for rootful builds.
> Clean up rootless.h, add optional Xina compatibility

- PassKitCore/PKPaymentDevice.h
- PassKitUI/PKPGSVSectionHeaderView.h
Headers i used for Apple Pay
Checklist
---------
…
…
> Apple Pay headers

- .github/workflows/compile-test.yml
The contents of this PR adds a GitHub Action that create a blank file, imports a single header, and then tries to verify the syntax stage of compiling with `clang`.
The above action is completed in a matrix with the following configurations:
Ubuntu and macOS, each with Obj-C and Obj-C++, each with ARC enabled and not.
See the 'relevant logs' section below to view these exact configurations.
No.
See jobs in https://github.com/leptos-null/theos-headers/actions/runs/4844610103
The `IOKit` …
> GitHub Action: Test syntax of headers in the repo

- rootless.h
See title
Checklist
---------
No
No
Linux (WSL)
> Fix XINA_SUPPORT `ROOT_PATH_NS_VAR` macro

- libroot.swiftmodule/arm64-apple-ios.swiftinterface
- libroot.swiftmodule/arm64e-apple-ios.swiftinterface
- libroot.swiftmodule/armv7-apple-ios.swiftinterface
Provide a Swift wrapper for libroot.
Since libroot will be widely used and Swift is a popular language to use with theos, I think providing a Swift interface for libroot is helpful.
This is implemented with `@_alwaysEmitIntoClient` so it effectively works like a `.a` library: if the functions are referenced, the functions will be pulled into the client.
The original source for this module is https://github.com/leptos-null/libroot-swift
Checklist
---------
no
no
Sample project:
- …
> [libroot] Add interface-only swiftmodule for libroot

- libroot/libroot.h
Update libroot to https://github.com/opa334/libroot/commit/102348f5e9360ad1f509ae4958bd3ca686347ee8
Checklist
---------
No
No
No
**Operating System:** macOS
**Platform:** Darwin
**Target Platform:** iOS
**Toolchain Version:** `Apple clang version 15.0.0 (clang-1500.3.9.4)`
**SDK Version:** 16.5
> Update to latest libroot (commit 102348f)

- HBLog.h
Changes HBLogDebug behaviour to match its pre-iOS10 implementation.
This change was discussed in #developers from the Chariz discord server.
**Operating System:** macOS Monterey
> Only keep HBLogDebug logs on 'DEBUG' builds

- rootless.h
Theos only links libroot when targeting `iphone`:
https://github.com/theos/theos/blob/351fbe83ee6058bdb64e90884c3bb047c31ab6c1/makefiles/instance/rules.mk#L139-L142
This is currently required because libroot is currently only compiled for iOS.
This PR seeks to match this linking behavior on the headers side:
Only include libroot if the target is iOS.
When libroot is not available, this PR uses the definitions that were previously used in a2a4086
I opted for this approach so that projects that target both iOS and macOS, in particular, can use macros from `rootless.h` without needing to shim these macros or provide separate code for each target.
Checklist
---------
Does this close any …
> Provide definitions for macros in rootless.h when !TARGET_OS_IPHONE

- MobileCoreServices/MobileCoreServices.h
- MobileCoreServices/module.modulemap
- MobileIcons/module.modulemap
This enables https://github.com/hbang/libcephei/commit/7ad69a903cffa0b8240f8eb1a9afb27c15d8fe57 to compile.
This PR adds module information for
- `MobileCoreServices`
- `MobileIcons`
Checklist
---------
https://github.com/hbang/libcephei/issues/58
No
No
**Operating System:** macOS
**Platform:** Darwin
**Target Platform:** iphone
**Toolchain Version:** `Apple clang version 15.0.0 (clang-1500.3.9.4)`
**SDK Version:** iPhoneOS16.5
> [MobileCoreServices,MobileIcons] Add modulemap

- UIKit/UIImageAsset+Private.h
Add `UIImageAsset+Private.h` header.
Checklist
---------
…
…
> [UIKit] Create UIImageAsset+Private.h

- rootless.h
libroot is not compiled for the simulator. 
To match this availability, use the fallback rootless macros when compiling for the simulator.
Checklist
---------
No
No
**Operating System:** macOS 15.3
**Platform:** Darwin
**Target Platform:** iphone, simulator
**Toolchain Version:** `Apple clang version 16.0.0 (clang-1600.0.26.6)`
**SDK Version:** `18.2`
> [rootless] Do not use libroot when targeting the simulator

- MobileCoreServices/LSApplicationProxy.h
- MobileCoreServices/LSBundleProxy.h
**Problems**:
1. The type of value `-entitlements` should be `NSDictionary <NSString *, id> *` or simply written as `NSDictionary *`, not `NSDictionary <NSString *, NSString *> *`. Which causes conflict when access non-string values in Swift.
2. Initializers of `LSApplicationProxy` and `LSBundleProxy` are treated as the same in Swift: `init(forIdentifier:)`. Which was ambiguous and caused error below (there’s no other way to call these methods in Swift):
**Fixes**:
1. Change return type of `-entitlements` to `NSDictionary <NSString *, id> *`.
2. Use macro `NS_SWIFT_NAME` to make explicit method signatures of these initializers.
**Before**:
**After**:
Checklist
---------
Does this close …
> Fix return value of entitlements & ambiguous initializers
